[workspace]
members = ["crates/qaptr-domain", "crates/qaptr-vault", "crates/qaptr-store"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[workspace.dependencies]
rusqlite = { version = "0.40.2", default-features = false, features = ["bundled"] }
age = "0.11.1"
fs2 = "0.4.3"
thiserror = "2.0"
xattr = "1.3.0"

[workspace.lints.rust]
warnings = "deny"
missing_docs = "deny"
unsafe_code = "deny"

[workspace.lints.clippy]
all = "warn"
