[package]
name = "qaptr-provider"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
contract = []

[dependencies]
qaptr-domain.workspace = true
qaptr-privacy = { path = "../qaptr-privacy" }
thiserror.workspace = true

[dev-dependencies]
qaptr-domain = { workspace = true, features = ["testing"] }

[lints]
workspace = true
